name: Update Lol Playlist

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch playlist content and update Lol.m3u
        run: |
          curl -s "https://github.com/aiemas/Mia/blob/main/sportzonline_lista.html" > index.html
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add Lol.m3u
          git commit -m "Update Lol.m3u from worker" || echo "No changes to commit"
          git pull --rebase origin main
          git push
